# Generated by Django 4.1.7 on 2023-04-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='timezone_str',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='utc_close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='utc_open_time',
            field=models.TimeField(null=True),
        ),
    ]
