# Generated by Django 4.1.7 on 2023-04-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_openhours_timezone_str_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenHours',
        ),
    ]
