# Generated by Django 4.1.7 on 2023-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_openhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('store_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('timezone_str', models.CharField(max_length=100, null=True)),
                ('local_open_time', models.TimeField()),
                ('local_close_time', models.TimeField()),
                ('utc_open_time', models.TimeField(null=True)),
                ('utc_close_time', models.TimeField(null=True)),
            ],
        ),
    ]
