# Generated by Django 4.1.7 on 2023-04-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenHours',
        ),
    ]
