# Generated by Django 4.1.7 on 2023-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHoursUTC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=25)),
                ('day', models.IntegerField()),
                ('timezone_str', models.CharField(max_length=100, null=True)),
                ('utc_open_time', models.TimeField()),
                ('utc_close_time', models.TimeField()),
            ],
        ),
    ]
